export const ADD_USER = "ADD_USER";
export const ADD_PROFILE = "ADD_PROFILE";
export const ADD_SUBCRIPTION = "ADD_SUBCRIPTION";
export const LOGIN_USER = "LOGIN_USER";
export const GET_COURSES = "GET_COURSES";
export const ADD_COURSES = "ADD_COURSES";
export const DELETE_SUBCRIPTION = "DELETE_SUBCRIPTION";